name: Build FBNeo APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build openjdk-11-jdk unzip wget git gcc g++ make autoconf libtool

      - name: Baixar Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip
          export ANDROID_NDK=$PWD/android-ndk-r23b
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Verificar se o script de compilação existe
        run: |
          if [ ! -f compile_fbneo_full.sh ]; then
            echo "Erro: O script de compilação não foi encontrado!"
            exit 1
          fi

      - name: Dar permissão ao script de compilação
        run: chmod +x compile_fbneo_full.sh

      - name: Compilar FBNeo
        run: |
          bash compile_fbneo_full.sh

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: fbneo-apk
          path: build_android/*.apk
